feat(standalone-mode): Enable using composite controller as a library
metacontroller/metacontroller pull request #304
Opened 2021-07-10 12:55 UTC by fpetkovski

Currently it is only possible to run Metacontroller as a cluster-wide
singletone. This mode requires deploying two additional CRDs,
CompositeController and DecoratorController.

This commit makes the changes needed to use composite controller
as a library from third-party applications. It introduces the standalone
mode and adds an example of how it can be used.

The following changes were made to the project structure:
* Expose the `composite.NewParentController` function as public
* Introduce `server/standalone.go` to help bootstrap a standalone controller
* Move existing examples to examples/server
* Introduce examples/standalone to illustrate library use

My initial suggestion is to announce this as an alpha feature since it is the first iteration and we don't yet know what could go wrong. Users who are in need of this solution can test it and provide feedback so that we can iron out the rough edges.

Relates to:
* https://github.com/metacontroller/metacontroller/issues/218
* https://github.com/metacontroller/metacontroller/issues/266

2021-07-10 13:29 UTC, grzesuav commented
hi @fpetkovski , thanks for contribution !

I will try to look next week or two, as I have busy weekend and want to finish logging change (which will be breaking ones, as they do change starting flags and  I want to clean up deprecated flags in the same release)

2021-07-10 16:18 UTC, fpetkovski commented
Hey @grzesuav no worries, take your time. There is no rush for reviewing this change :)

2021-07-26 21:34 UTC, grzesuav commented
hi @fpetkovski , can you rebase upon 2.0.0 ? I will take a look in next few days on this

2021-07-28 10:45 UTC, fpetkovski commented
@grzesuav the PR should be rebased with all tests passing :)

2021-07-28 15:23 UTC, grzesuav commented
I wonder if we could have `library` subdirectory in `examples`, as it would keep it on one place. Otherwise I do not have much suggestions. Want just to node that this will be considered as alpha feature, as I cannot guarantee API stability for now. I have in mind also using `goreleaser`  for building and pushing images, and pushing the docs to `go pkg` site, would also help with using as library, but it will be a rather long-term goal.

2021-07-28 15:24 UTC, grzesuav requested changes
Can you move `examples-standalone` into `examples` directory ? Name like `standalone` or `library` would be good enough I think

2021-07-28 15:37 UTC, grzesuav commented on pkg/dynamic/discovery/discovery.go
> +func (rm *ResourceMap) WaitForSync() {
I know if it mostly not present in the code, but if we wish to make it an API I would ask to add documentation there in form in godoc comments on public methods

2021-07-28 15:39 UTC, grzesuav commented
cold you check if writing a integration test (like in `test/integration`) would work for this library mode ? It would let us know about API changes

2022-08-11 16:33 UTC, grzesuav commented
@fpetkovski as this PR is a bit stale I created issue for that https://github.com/metacontroller/metacontroller/issues/604, closing this as it got diverged

2022-08-11 16:33 UTC, closed without merging

2022-08-16 05:43 UTC, fpetkovski commented
No problem. This somehow dropped off my radar completely. I can revisit it if a need arises again :)