fix: Add command line arguments parameterization to Helm chart
metacontroller/metacontroller pull request #364
Opened 2021-09-16 14:54 UTC by VictorBac

2021-09-17 15:44 UTC, grzesuav commented
hi @VictorBac thanks for the PR, could hou however change the commit title to `fix: Add command line arguments parameterization to Helm chart`  to make it more obvius what it is about ?

2021-09-17 15:45 UTC, grzesuav requested changes
1. Please adjust commit message
2. Please add parameter descriptions to https://metacontroller.github.io/metacontroller/guide/helm-install.html in https://github.com/metacontroller/metacontroller/blob/master/docs/src/guide/helm-install.md

2021-09-17 17:11 UTC, VictorBac commented
Done, but I am not sure about the default value for zap.devel:
https://sdk.operatorframework.io/docs/building-operators/golang/references/logging/

I let it empty, if someone needs it they will know how to use it ^^'

2021-09-17 20:24 UTC, grzesuav commented on deploy/helm/metacontroller/Chart.yaml
> -version: v2.0.10
do not need to update this, the release automation will bump it, please restore it as it was

2021-09-17 20:25 UTC, grzesuav commented on docs/src/guide/helm-install.md
> +| `zap.devel`                               | Development Mode or Production Mode           | `""`                                                    |
default should be producion, so logging in json etc

2021-09-21 20:48 UTC, VictorBac commented
Thank you @grzesuav , I fixed

2021-09-26 17:45 UTC, grzesuav approved these changes

2021-09-26 19:00 UTC, merged

2021-09-26 19:12 UTC, grzesuav commented
:tada: This PR is included in version 2.0.12 :tada:

The release is available on [GitHub release](https://github.com/metacontroller/metacontroller/releases/tag/v2.0.12)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: