feat: Adding java controller example using spring-boot
metacontroller/metacontroller pull request #565
Opened 2022-07-18 13:39 UTC by salaboy

Adding Java / Spring Boot controller example. 

This project can be built using maven (which comes with the example) and optionally deployed with Knative Functions, but normal Kubernetes deployment can be used as well. 

The example reconciles a new CRD which checks some websites to be up, and if they are all up a new Deployment is created. 

The project also includes a test and a README explaining how to use this example with MetaController. 

PS: feedback is appreciated

2022-07-18 20:48 UTC, grzesuav requested changes
HI, several comments :
* please remove `DS_Store` files
* please add a `test.sh` like https://github.com/metacontroller/metacontroller/blob/master/examples/globalconfigmap/test.sh which will install, execute and clean up controller

2022-07-18 20:48 UTC, grzesuav commented on examples/java/spring-boot/internet-controller/README.md
> +This project was created to demonstrate how to use MetaController and Knative Functions. This controller shows how to monitor the internet and trigger some internet production tests only when the app
`how to monitor the internet` -> please be more specific, what exactly is being  monitored ? Some upstream service etc ?

2022-07-18 20:48 UTC, grzesuav commented on examples/java/spring-boot/internet-controller/README.md
> +  - `HELM_EXPERIMENTAL_OCI=1 helm pull oci://ghcr.io/metacontroller/metacontroller-helm --version=v2.2.5` to fetch the metacontroller chart
`v2.2.5` is very old, please switch to the lates release

2022-07-18 20:48 UTC, grzesuav commented on examples/java/spring-boot/internet-controller/config/controller-deploy.yaml
> +  name: metacontroller
I think it will be created via helm chart anyway

2022-07-18 20:51 UTC, grzesuav commented
@AmitKumarDas @mikesmithgh WDYT ? My only concern is  that do not demonstrates any particular behavior of metacontroller

2022-07-19 06:25 UTC, AmitKumarDas commented
> @AmitKumarDas @mikesmithgh WDYT ? My only concern is that do not demonstrates any particular behavior of metacontroller

I am a bit hesitant on adding codebases into this main repo esp. since the same has to be maintained e.g. security vulnerabilities, dependency updates & stuff. I understand that this is part of examples but the amount of files involved here is significant.

Again I understand sprint boot is quite popular at end users' & above comment is certainly not meant to discourage the community.

2022-07-19 14:05 UTC, salaboy commented
I will fix the requested changes, and I can make the example a bit more simple.

The current example shows how to create children resources and how to reconcile based on the payload that is created by metacontroller. I am happy to show more metacontroller features.. can you please suggest some? 

I am also happy to help maintaining this. 

My intention by creating the PR was to get feedback because it will be great to have some java specific examples here to make it easy for the java folks to get involved.

2022-07-19 14:48 UTC, AmitKumarDas commented
> I will fix the requested changes, and I can make the example a bit more simple.
> 
> The current example shows how to create children resources and how to reconcile based on the payload that is created by metacontroller. I am happy to show more metacontroller features.. can you please suggest some?
> 
> I am also happy to help maintaining this.
> 
> My intention by creating the PR was to get feedback because it will be great to have some java specific examples here to make it easy for the java folks to get involved.

@salaboy It will be great if you can maintain the example.

2022-07-21 13:10 UTC, salaboy commented
@AmitKumarDas ok.. I am happy to maintain or find someone else to help me maintain the example.. If you ever need changes to be applied I am also happy to be assigned to issues related with the example too.

2022-07-21 13:11 UTC, salaboy commented
I am currently off until monday.. so I will work on the changes as soon as I get back to work

2022-07-28 07:22 UTC, salaboy commented
Crazy week here.. I am still catching up.. but I haven't forgotten this one.. I will work on this asap

2023-08-11 23:47 UTC, grzesuav commented
closing for now @salaboy

2023-08-11 23:47 UTC, closed without merging