fix(examples): [#83] - Fix service-per-port sync hook
metacontroller/metacontroller pull request #84
Opened 2020-12-04 19:29 UTC by fpetkovski

In Later versions of kubernetes service ports with multiple ports need to have names for their ports.

This MR fixes the service-per-pod example

2020-12-05 03:00 UTC, AmitKumarDas approved these changes

2020-12-06 17:40 UTC, grzesuav commented
hi @fpetkovski , can you change commit prefix to `chore` as this should not trigger a release ?

2020-12-06 17:47 UTC, grzesuav requested changes
change commit prefix to `chore` instead of `fix

2020-12-06 18:24 UTC, fpetkovski commented
Sure thing, should be done

2020-12-06 19:48 UTC, grzesuav approved these changes

2020-12-06 19:48 UTC, grzesuav commented
thanks for contribution !

2020-12-06 19:48 UTC, merged

2020-12-10 07:44 UTC, grzesuav commented
:tada: This PR is included in version 1.0.1 :tada:

The release is available on [GitHub release](https://github.com/metacontroller/metacontroller/releases/tag/v1.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: