feat(perf): Add a flag to configure the number of workers to run
metacontroller/metacontroller pull request #89
Opened 2020-12-12 11:24 UTC by maljub01

This enables users to control how many webhook requests get processed in parallel.

2020-12-12 14:15 UTC, grzesuav requested changes
@maljub01 thanks for contribution !

Can you add flag description to documentation ? in metacontroller/docs/src/guide/install.md

2020-12-13 11:32 UTC, grzesuav commented
Also, rebase on current master will solve issue with docker lint

2020-12-14 10:20 UTC, AmitKumarDas approved these changes

2020-12-14 14:01 UTC, grzesuav approved these changes

2020-12-14 14:01 UTC, merged

2020-12-14 14:06 UTC, grzesuav commented
:tada: This PR is included in version 1.1.0 :tada:

The release is available on [GitHub release](https://github.com/metacontroller/metacontroller/releases/tag/v1.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: